<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="images/bonbon.ico" />
       <link rel="stylesheet" href="css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <title>M.BONBON</title>
    <link rel="stylesheet" href="css/style.css">
     <script src="js/function.js"></script>
</head>

<body>
    <div class="container">
        <img src="images/logo.png" width="100%" height="100%" class="image-fluid" >
        
            <nav class="navbar navbar-expand-lg bg-danger ">
                <div class="container-fluid ">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse " id="navbarNav">
                        <ul class="navbar-nav text-white">
                            <li class="nav-item">
                                <a class="nav-link " aria-current="page" href="index.php">M.BONBON</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="ajouterProduit.php"> ajouter Produit</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="ModifierProduit.php">Modifier Produit</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="SupprimerProduit.php">Supprimer Produit</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
            <br>
       <div class="text-center" id="date"> </div>
        
           